# Site settings
title: About me
email: jckkinyanjui@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My website description goes here.

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# GitHub Pages settings
remote_theme: owner/repo
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jck-bit.github.io" # the base hostname & protocol for your site
